import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Layout from '../components/Layout'
import { Philosophy } from '../components/Philosophy'
import WorkExperience from '../components/WorkExperience'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Cephas Chapa | Fullstack Web Developer - NodeJs, ExpressJs, MongoDB, ReactJS, NextJs, EcmaScript, JavaScript</title>
         
        {/* Meta */}
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="I am professioal web developer specializing in JavaScript. I build NodeJs applications with frameworks like ReactJs, NextJs, ExpressJs and NodeJs"/>
        <meta name='robots' content='index, follow'/>
        <meta property="og:type" content="Cephas Chapa - ReactJs | NextJs | NodeJs | ExpressJs | MongoDB" />
        <meta property="og:title" content="Cephas Chapa - Potforlio" />
        <meta property="og:description" content="I am professioal web developer specializing in JavaScript. I build NodeJs applications with frameworks like ReactJs, NextJs, ExpressJs and NodeJs" />
        <meta property="og:image" content="LINK TO THE IMAGE FILE" />
        <meta property="og:url" content="https://iamcephas.vercel.app/" />
        <meta property="og:site_name" content="Cephas Chapa - Potforlio" />
        
        {/* Links */}
        <link rel='canonical' href='http://iamcephas.vercel.app/'/>
        <link rel="icon" href="/favicon.ico" />

      </Head>
      {/* Body */}
      {/* Layout */}
      <Layout>
        <Hero />
        {/* Word Experience */}
        <WorkExperience />
        {/* Philosophy */}
        <Philosophy/>
      </Layout>  
    </div>
  )
}
